.PHONY: all container upload

all: container

container:
	echo "WARNING: making a single arch container, do not upload to hub"
	./make-container.sh

upload:
	echo "WARNING: make upload is deprecated as container probably only single arch"
	./upload-container.sh
